Move zip config to end
mendix/hybrid-app-base pull request #50
Opened 2019-10-21 12:50 UTC by mmehmetAliIzci

Related to issue: https://github.com/mendix/hybrid-app-base/issues/37

Fixes an issue where configs were not copied to zip file.

2019-11-04 13:06 UTC, jogboms commented on webpack.config.js
> +    // Merge zip later because its not copying configs in if
Could there be more info on this?

2019-11-05 10:59 UTC, smarki requested changes

2019-11-05 10:59 UTC, smarki commented on webpack.config.js
> +    // Merge zip later because its not copying configs in if
if?

2019-11-05 10:59 UTC, smarki commented on package.json
> +  "version": "4.1.5",
No reason to up the version till we actually do a tag and release for it

2019-11-05 10:59 UTC, smarki commented on webpack.config.js
> +    })
;

2019-11-05 11:51 UTC, jogboms commented on package.json
> +  "version": "4.1.5",
True.

2019-11-05 11:52 UTC, jogboms commented on webpack.config.js
> +    })
Missed

2019-11-05 12:09 UTC, smarki approved these changes

2019-11-05 12:09 UTC, merged